routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

// data obat
Route::get('/crud', 'CrudController@index')->name('crud');
Route::get('/crud/add', 'CrudController@add')->name('cr.t');
Route::get('crud/edit', 'CrudController@edit')->name('cr.e');
Route::post('crud/save', 'CrudController@save')->name('cr.save');
Route::delete('crud/delete/{id}', 'CrudController@delete')->name('cr.delete');
Route::get('crud/{id}/edit', 'CrudController@edit')->name('cr.edit');
Route::patch('crud/{id}', 'CrudController@update')->name('cr.update');

// bagian betuk obat
Route::get('/Bentuk_obat', 'Bentuk_obatController@index')->name('do');
Route::get('/Bentuk_obat/add', 'Bentuk_obatController@add')->name('do.t');
Route::post('/Bentuk_obat/save', 'Bentuk_obatController@save')->name('do.save');
Route::delete('/Bentuk_obat/delete/{id}', 'Bentuk_obatController@delete')->name('do.delete');
Route::get('/Bentuk_obat/{id}/edit', 'Bentuk_obatController@edit')->name('do.edit');
Route::patch('/Bentuk_obat/{id}', 'Bentuk_obatController@update')->name('do.update');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function () {
    Route::resource('/users', 'UserController', ['except' => ['show', 'store']]);
    Route::get('/users/addUser', 'UserController@add')->name('users.t');
    Route::post('/users/save', 'UserController@save')->name('users.save');
    Route::delete('/users/delete/{id}', 'UserController@delete')->name('users.delete');
    Route::get('users/{id}/edit', 'UserController@edit')->name('users.edit');
    Route::patch('users/{id}', 'UserController@update')->name('users.update');
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, HasRoles;

    // protected $table = 'users';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'status',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function role()
    {   
        // return $this->belongsToMany('App\Role', 'roles', 'id');
        return $this->belongsToMany('App\Role');
        // return $this->belongsToMany(Role::class, 'roles');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\User;
use App\Role;
use Illuminate\Http\Request;
use Illuminate\Foundation\Auth\RegistersUsers;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;


class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
    }

    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name_user' => ['required', 'string', 'max:255'],
            'email_user' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'pass_user' => ['required', 'string', 'min:8', 'confirmed'],
        ]);
    }

    private function _validation(Request $request)
    {

        $validation = $request->validate(
            [
                'name' => 'required|string|max:255',
                'email' => 'required|string|max:100',
                'password' => 'required|string|min:8',
            ],
            [

                'name.required' => 'Harus Diisi!',
                'name.max' => 'Maksimal 255 Karakter!',
                'name.min' => 'Minimal 5 Karakter!',

                'email.required' => 'Harus Diisi!',
                'email.max' => 'Maksimal 255 Karakter!',
                'email.min' => 'Minimal 5 Karakter!',

                'password.required' => 'Harus Diisi!',
                'password.max' => 'Maksimal 255 Kotak!',
                'password.min' => 'Minimal 8 Kotak!',

            ]
        );
    }

    public function index()
    {
        $users = User::all();
        return view('admin.users.index')->with('users', $users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function add()
    {
        $roles = Role::all();
        return view('admin.users.addUser',['roles' => $roles]);
    }
    public function create()
    {
        // return User::create([
        //     'name_user' => $data['name'],
        //     'email_user' => $data['email'],
        //     'pass_user' => Hash::make($data['password']),
        //     'status' => 1,
        // ]);
        // return redirect()->route('admin.users.index',[
        //     'users' => $users,
        //     'roles' => $roles
        // ])->with('message', 'Data Berhasil Disimpan!');
    }
    public function save(Request $data)
    {
        $user = User::create([
            'name' => $data->nama_user,
            'email' => $data->email_user,
            'status' => 1,
            'password' => Hash::make($data['password_user']),            
        ]);

        $user->assignRole($data->role);

        return redirect()->route('admin.users.index')->with('message', 'Data Berhasil Disimpan!');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $roles = Role::all();
        $users = DB::table('users')->where('id', $id)->first();
        return view('admin.users.editUser', [
            'users' => $users,
            'roles' => $roles
            ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $user->roles()->sync($request->role);
        DB::table('users')->where('id', $user->id)->update([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request['password']),
        ]);
        return redirect()->route('admin.users.index')->with('message', 'Data Berhasil Diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        // DB::table('users')->where('id', $user)->delete();
        // return redirect()->back()->with('message', 'Data Berhasil Dihapus!');
    }

    //method hapus data
    public function delete($id)
    {
        DB::table('users')->where('id', $id)->delete();
        return redirect()->back()->with('message', 'Data Berhasil Dihapus!');
    }
}

resources/views/admin/users/addUser.blade.php
@extends('layouts.master')
@section('title','')


@section('content')
<div class="section-body">
</div>

<div class="buttons">
    <div class="card">
        <div class="card-header">
          <h4>Tambah User</h4>
        </div>
        <div class="card-body">
          <div class="alert alert-info">
            <b>Note!</b> Pastikan Isi data dengan Baik dan Benar!
          </div>
         <form action="{{route('admin.users.save')}}" method="POST" enctype="multipart/form-data">
          @csrf
          <div class="form-group">
            <label for="nama_user" @error('nama_user')
                class="text-danger"
            @enderror> Nama User @error('nama_user')
               {{$message}}
              @enderror</label>
            <x-input field="nama_user" label="" type="text" class="form-control" value="nama_user" placeholder="Nama User.."></x-input>
          </div>

          <div class="form-group">
            <label for="email_user" @error('email_user')
                class="text-danger"
            @enderror> Email User @error('email_user')
               {{$message}}
              @enderror</label>
            <x-input field="email_user" label="" type="text" value="email_user" class="form-control" placeholder="Email User.."></x-input>
          </div>

          <div class="form-group">
            <label for="pass_user" @error('pass_user')
                class="text-danger"
            @enderror> Password User @error('pass_user')
               {{$message}}
              @enderror</label>
            <x-input field="pass_user" label="" type="text" class="form-control" placeholder="Password User.."></x-input>
          </div>
        </div>
        <div class="form-group">
            <label for="password" @error('password') class="text-danger" @enderror> Role @error('password') {{$message}} @enderror</label>
            <div class="form-check">
              
              @foreach ($roles as $role)
              <input type="checkbox" value="{{$role->id}}" name="role[]">
              <label>{{$role->name}}</label>
              @endforeach
            </div>
          </div>
        <div class="card-footer text-right">
          <button class="btn btn-primary mr-1" type="submit">Submit</button>
          <button class="btn btn-secondary" type="reset">Reset</button>
        </div>
      </form>
      </div>
    </div>
  </div>
@endsection
@push('page-scripts')
@endpush

resources/views/admin/users/editUser.blade.php
@extends('layouts.master')
@section('title','')


@section('content')
<div class="section-body">
</div>

<div class="buttons">
    <div class="card">
        <div class="card-header">
          <h4>Data User</h4>
        </div>
        <div class="card-body">
          <div class="alert alert-info">
            <b>Note!</b> Pastikan Isi data dengan Baik dan Benar!
          </div>
         <form action="{{route('admin.users.update',$users->id)}}"  method="POST" enctype="multipart/form-data">
          @csrf
          @method ('patch')
          <div class="form-group">
            <label for="name" @error('nama_user')
                class="text-danger"
            @enderror> Nama User @error('name')
               {{$message}}
              @enderror</label>
            <input name="name"  type="text"
            @if (old('name'))
              value="{{old('name')}}"
            @else
              value="{{$users->name}}"
            @endif
            class="form-control" ></input>
          </div>

          <div class="form-group">
            <label for="email" @error('email')
                class="text-danger"
            @enderror> Email User @error('email')
               {{$message}}
              @enderror</label>
            <input name="email"  type="text"
            @if (old('email'))
              value="{{old('email')}}"
            @else
              value="{{$users->email}}"
            @endif
            class="form-control" ></input>
          </div>

          <div class="form-group">
            <label for="password" @error('password')
                class="text-danger"
            @enderror> Password User @error('password')
               {{$message}}
              @enderror</label>
            <input name="password"  type="text"
            @if (old('password'))
              value="{{old('password')}}"
            @else
              value="{{$users->password}}"
            @endif
            class="form-control" ></input>
          </div>

          <div class="form-group">
            <label for="password" @error('password') class="text-danger" @enderror> Role @error('password') {{$message}} @enderror</label>
            <div class="form-check">
              
              @foreach ($roles as $role)
              <input type="checkbox" value="{{$role->id}}" name="role[]">
              <label>{{$role->name}}</label>
              @endforeach
            </div>
          </div>

        <div class="card-footer text-right">
          <button class="btn btn-primary mr-1" type="submit">Submit</button>
          <button class="btn btn-secondary" type="reset">Reset</button>
        </div>
      </form>
      </div>
    </div>


  </div>
@endsection
@push('page-scripts')

@endpush

resources/views/admin/users/index.blade.php
@extends('layouts.master')
@section('title','')


@section('content')
<div class="section-body">
  <div class="row" >
    <div class="col-12 col-md-12 col-lg-12">
      <div class="buttons">
        <a href="{{route('admin.users.t')}}" class="btn btn-outline-primary">Tambah Data+</a>
        <table class="table table-striped table-bordered">
          <tr>
            <th>No.</th>
            <th scope="col">Nama </th>
            <th scope="col">Email</th>
            <!-- <th scope="col">Roles</th> -->
            <th scope="col">Aksi</th>
          </tr>
          @php $no = 1; @endphp
          @foreach ($users as $data)
          <tr>
            <td>{{$no++}}</td>
            <td>{{$data->name}}</td>
            <td>{{$data->email}}</td>
            <td>{{ implode(',', $data->roles()->get()->pluck('name')->toArray()) }}</td>
            <td>
              <a type="button" href="{{route('admin.users.edit',$data->id)}}" class="badge badge-warning">Ubah</a>
              {{-- <a href="#"  data-id="{{$data->id}}" class="badge badge-danger swal-1"> --}}
                <form  id="delete{{$data->id}}" action="{{route('admin.users.delete',$data->id)}}" method="POST">
                @csrf
                @method('delete')
                {{-- <input type="button" value="Delete" class="badge badge-danger swal-1"/> --}}
                <button class="badge badge-danger swal-1" style="border: none"> delete </button>
                </form>
            </td>
          </tr>
          @endforeach
        </table>
      </div>

    </div>


  </div>
</div>



@endsection
@push('page-scripts')
       <script src="{{asset('assets/js/page/modules-sweetalert.js')}}"> </script>
       <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
@endpush

@push('after-scripts')
<script>
$(".swal-1").click(function(e) {
    id = e.target.dataset.id;
    swal({
        title: 'Yakin Hapus Data?',
        text: 'Data yang dihapus tidak bisa dikembalikan!',
        icon: 'warning',
        buttons: true,
        dangerMode: true,
      })
      .then((willDelete) => {
        if (willDelete) {
       swal('Poof! Hapus Data!', {
         icon: 'success',
        });
        $(`#delete${id}`).submit();
        } else {
          swal('Batal Hapus Data!');
        }
      });
  });
</script>

@endpush