routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

// data obat
Route::get('/crud', 'CrudController@index')->name('crud');
Route::get('/crud/add', 'CrudController@add')->name('cr.t');
Route::get('crud/edit', 'CrudController@edit')->name('cr.e');
Route::post('crud/save', 'CrudController@save')->name('cr.save');
Route::delete('crud/delete/{id}', 'CrudController@delete')->name('cr.delete');
Route::get('crud/{id}/edit', 'CrudController@edit')->name('cr.edit');
Route::patch('crud/{id}', 'CrudController@update')->name('cr.update');

// bagian betuk obat
Route::get('/Bentuk_obat', 'Bentuk_obatController@index')->name('do');
Route::get('/Bentuk_obat/add', 'Bentuk_obatController@add')->name('do.t');
Route::post('/Bentuk_obat/save', 'Bentuk_obatController@save')->name('do.save');
Route::delete('/Bentuk_obat/delete/{id}', 'Bentuk_obatController@delete')->name('do.delete');
Route::get('/Bentuk_obat/{id}/edit', 'Bentuk_obatController@edit')->name('do.edit');
Route::patch('/Bentuk_obat/{id}', 'Bentuk_obatController@update')->name('do.update');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function () {
    Route::resource('/users', 'UserController', ['except' => ['show', 'store']]);
    Route::get('/users/addUser', 'UserController@add')->name('users.t');
    Route::post('/users/save', 'UserController@save')->name('users.save');
    Route::delete('/users/delete/{id}', 'UserController@delete')->name('users.delete');
    Route::get('users/{id}/edit', 'UserController@edit')->name('users.edit');
    Route::patch('users/{id}', 'UserController@update')->name('users.update');
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/header.blade.php
<nav class="navbar navbar-expand-lg main-navbar">
    <form class="form-inline mr-auto">
      <ul class="navbar-nav mr-3">
        <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
        <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li>
      </ul>
      <div class="search-element">
        <input class="form-control" type="search" placeholder="Search" aria-label="Search" data-width="250">
        <button class="btn" type="submit"><i class="fas fa-search"></i></button>
        <div class="search-backdrop"></div>
        <div class="search-result">
          <div class="search-header">
            Histories
          </div>
          <div class="search-item">
            <a href="#">How to hack NASA using CSS</a>
            <a href="#" class="search-close"><i class="fas fa-times"></i></a>
          </div>
          <div class="search-item">
            <a href="#">Kodinger.com</a>
            <a href="#" class="search-close"><i class="fas fa-times"></i></a>
          </div>
          <div class="search-item">
            <a href="#">#Stisla</a>
            <a href="#" class="search-close"><i class="fas fa-times"></i></a>
          </div>
          <div class="search-header">
            Result
          </div>
          <div class="search-item">
            <a href="#">
              <img class="mr-3 rounded" width="30" src="../assets/img/products/product-3-50.png" alt="product">
              oPhone S9 Limited Edition
            </a>
          </div>
          <div class="search-item">
            <a href="#">
              <img class="mr-3 rounded" width="30" src="../assets/img/products/product-2-50.png" alt="product">
              Drone X2 New Gen-7
            </a>
          </div>
          <div class="search-item">
            <a href="#">
              <img class="mr-3 rounded" width="30" src="../assets/img/products/product-1-50.png" alt="product">
              Headphone Blitz
            </a>
          </div>
          <div class="search-header">
            Projects
          </div>
          <div class="search-item">
            <a href="#">
              <div class="search-icon bg-danger text-white mr-3">
                <i class="fas fa-code"></i>
              </div>
              Stisla Admin Template
            </a>
          </div>
          <div class="search-item">
            <a href="#">
              <div class="search-icon bg-primary text-white mr-3">
                <i class="fas fa-laptop"></i>
              </div>
              Create a new Homepage Design
            </a>
          </div>
        </div>
      </div>
    </form>
    <ul class="navbar-nav navbar-right">
      <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
        <img alt="image" src="../assets/img/avatar/avatar-1.png" class="rounded-circle mr-1">
        <div class="d-sm-none d-lg-inline-block">
          Hi, {{ Auth::user()->name }}
        </div></a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{{ route('logout') }}"
            onclick="event.preventDefault();
              document.getElementById('logout-form').submit();">
              {{ __('Logout') }}
          </a>
          <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
            @csrf
          </form>
          <a class="dropdown-item" href="{{ route('admin.users.index') }}">
            User Management
          </a>
        </div>
      </li>
    </ul>
  </nav>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title>@yield('title')  {{config('app.name')}}</title>

  <!-- General CSS Files -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

  <!-- CSS Libraries -->

  <!-- Template CSS -->
  <link rel="stylesheet" href="{{asset('assets/css/style.css')}}">
  <link rel="stylesheet" href="{{asset('assets/css/components.css')}}">
  @stack('pages-styles')
</head>

<body>
  <div id="app">
    <div class="main-wrapper">
      <div class="navbar-bg"></div>
      @include('layouts.header')
      @include('layouts.sidebar')

      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>Sistem Inventory Apotek</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="#">Dasboard</a></div>
                <div class="breadcrumb-item"><a href="#">Bootstrap Components</a></div>
                <div class="breadcrumb-item">Form</a></div>
            </div>
          </div>

          @yield('content')
        </section>
      </div>
      <footer class="main-footer">
        <div class="footer-left">
         <!-- DISINI FOOTER KONTEN! --> 
        </div>
        <div class="footer-right">
          2.3.0
        </div>
      </footer>
    </div>
  </div>
  @stack('before-scripts')
  <!-- General JS Scripts -->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>

  <script src="{{asset('assets/js/stisla.js')}}"></script>

  <!-- JS Libraies -->
  @stack('page-scripts')

  <!-- Template JS File -->
  <script src="{{asset('assets/js/scripts.js')}}"></script>
  <script src="{{asset('assets/js/custom.js')}}"></script>
  @stack('after-scripts')
  <!-- Page Specific JS File -->
</body>
</html>

resources/views/layouts/sidebar.blade.php
<div class="main-sidebar">
    <aside id="sidebar-wrapper">
      <div class="sidebar-brand">
        <a href="index.html">Stisla</a>
      </div>
      <div class="sidebar-brand sidebar-brand-sm">
        <a href="index.html">St</a>
      </div>
      <ul class="sidebar-menu">
          <li class="menu-header">Dashboard</li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link has-dropdown"><i class="fas fa-fire"></i><span>Dashboard</span></a>
            <ul class="dropdown-menu">
              <li><a class="nav-link" href="index-0.html">General Dashboard</a></li>
              <li><a class="nav-link" href="index.html">Ecommerce Dashboard</a></li>
            </ul>
          </li>
          <li class="menu-header">Starter</li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-columns"></i> <span>Layout</span></a>
            <ul class="dropdown-menu">
              <li><a class="nav-link" href="layout-default.html">Default Layout</a></li>
              <li><a class="nav-link" href="layout-transparent.html">Transparent Sidebar</a></li>
              <li><a class="nav-link" href="layout-top-navigation.html">Top Navigation</a></li>
            </ul>
          </li>
          <li class="active"><a class="nav-link" href="{{route('crud')}}"><i class="far fa-square"></i> <span>Data Obat</span></a></li>
         <!-- <li class="nav-item dropdown">
            <a href="#" class="nav-link has-dropdown"><i class="fas fa-th"></i> <span>Bootstrap</span></a>
            <ul class="dropdown-menu">
              <li><a class="nav-link" href="bootstrap-alert.html">Alert</a></li>
              <li><a class="nav-link" href="bootstrap-badge.html">Badge</a></li>
              <li><a class="nav-link" href="bootstrap-breadcrumb.html">Breadcrumb</a></li>
              <li><a class="nav-link" href="bootstrap-buttons.html">Buttons</a></li>
              <li><a class="nav-link" href="bootstrap-card.html">Card</a></li>
              <li><a class="nav-link" href="bootstrap-carousel.html">Carousel</a></li>
              <li><a class="nav-link" href="bootstrap-collapse.html">Collapse</a></li>
              <li><a class="nav-link" href="bootstrap-dropdown.html">Dropdown</a></li>
              <li><a class="nav-link" href="bootstrap-form.html">Form</a></li>
              <li><a class="nav-link" href="bootstrap-list-group.html">List Group</a></li>
              <li><a class="nav-link" href="bootstrap-media-object.html">Media Object</a></li>
              <li><a class="nav-link" href="bootstrap-modal.html">Modal</a></li>
              <li><a class="nav-link" href="bootstrap-nav.html">Nav</a></li>
              <li><a class="nav-link" href="bootstrap-navbar.html">Navbar</a></li>
              <li><a class="nav-link" href="bootstrap-pagination.html">Pagination</a></li>
              <li><a class="nav-link" href="bootstrap-popover.html">Popover</a></li>
              <li><a class="nav-link" href="bootstrap-progress.html">Progress</a></li>
              <li><a class="nav-link" href="bootstrap-table.html">Table</a></li>
              <li><a class="nav-link" href="bootstrap-tooltip.html">Tooltip</a></li>
              <li><a class="nav-link" href="bootstrap-typography.html">Typography</a></li>
            </ul>
          </li>
          <li class="menu-header">Stisla</li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link has-dropdown"><i class="fas fa-th-large"></i> <span>Components</span></a>
            <ul class="dropdown-menu">
              <li><a class="nav-link" href="components-article.html">Article</a></li>
              <li><a class="nav-link beep beep-sidebar" href="components-avatar.html">Avatar</a></li>
              <li><a class="nav-link" href="components-chat-box.html">Chat Box</a></li>
              <li><a class="nav-link beep beep-sidebar" href="components-empty-state.html">Empty State</a></li>
              <li><a class="nav-link" href="components-gallery.html">Gallery</a></li>
              <li><a class="nav-link beep beep-sidebar" href="components-hero.html">Hero</a></li>
              <li><a class="nav-link" href="components-multiple-upload.html">Multiple Upload</a></li>
              <li><a class="nav-link beep beep-sidebar" href="components-pricing.html">Pricing</a></li>
              <li><a class="nav-link" href="components-statistic.html">Statistic</a></li>
              <li><a class="nav-link" href="components-tab.html">Tab</a></li>
              <li><a class="nav-link" href="components-table.html">Table</a></li>
              <li><a class="nav-link" href="components-user.html">User</a></li>
              <li><a class="nav-link beep beep-sidebar" href="components-wizard.html">Wizard</a></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link has-dropdown"><i class="far fa-file-alt"></i> <span>Forms</span></a>
            <ul class="dropdown-menu">
              <li><a class="nav-link" href="forms-advanced-form.html">Advanced Form</a></li>
              <li><a class="nav-link" href="forms-editor.html">Editor</a></li>
              <li><a class="nav-link" href="forms-validation.html">Validation</a></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link has-dropdown"><i class="fas fa-map-marker-alt"></i> <span>Google Maps</span></a>
            <ul class="dropdown-menu">
              <li><a href="gmaps-advanced-route.html">Advanced Route</a></li>
              <li><a href="gmaps-draggable-marker.html">Draggable Marker</a></li>
              <li><a href="gmaps-geocoding.html">Geocoding</a></li>
              <li><a href="gmaps-geolocation.html">Geolocation</a></li>
              <li><a href="gmaps-marker.html">Marker</a></li>
              <li><a href="gmaps-multiple-marker.html">Multiple Marker</a></li>
              <li><a href="gmaps-route.html">Route</a></li>
              <li><a href="gmaps-simple.html">Simple</a></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link has-dropdown"><i class="fas fa-plug"></i> <span>Modules</span></a>
            <ul class="dropdown-menu">
              <li><a class="nav-link" href="modules-calendar.html">Calendar</a></li>
              <li><a class="nav-link" href="modules-chartjs.html">ChartJS</a></li>
              <li><a class="nav-link" href="modules-datatables.html">DataTables</a></li>
              <li><a class="nav-link" href="modules-flag.html">Flag</a></li>
              <li><a class="nav-link" href="modules-font-awesome.html">Font Awesome</a></li>
              <li><a class="nav-link" href="modules-ion-icons.html">Ion Icons</a></li>
              <li><a class="nav-link" href="modules-owl-carousel.html">Owl Carousel</a></li>
              <li><a class="nav-link" href="modules-sparkline.html">Sparkline</a></li>
              <li><a class="nav-link" href="modules-sweet-alert.html">Sweet Alert</a></li>
              <li><a class="nav-link" href="modules-toastr.html">Toastr</a></li>
              <li><a class="nav-link" href="modules-vector-map.html">Vector Map</a></li>
              <li><a class="nav-link" href="modules-weather-icon.html">Weather Icon</a></li>
            </ul>
          </li>
          <li class="menu-header">Pages</li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link has-dropdown"><i class="far fa-user"></i> <span>Auth</span></a>
            <ul class="dropdown-menu">
              <li><a href="auth-forgot-password.html">Forgot Password</a></li>
              <li><a href="auth-login.html">Login</a></li>
              <li><a class="beep beep-sidebar" href="auth-login-2.html">Login 2</a></li>
              <li><a href="auth-register.html">Register</a></li>
              <li><a href="auth-reset-password.html">Reset Password</a></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link has-dropdown"><i class="fas fa-exclamation"></i> <span>Errors</span></a>
            <ul class="dropdown-menu">
              <li><a class="nav-link" href="errors-503.html">503</a></li>
              <li><a class="nav-link" href="errors-403.html">403</a></li>
              <li><a class="nav-link" href="errors-404.html">404</a></li>
              <li><a class="nav-link" href="errors-500.html">500</a></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link has-dropdown"><i class="fas fa-bicycle"></i> <span>Features</span></a>
            <ul class="dropdown-menu">
              <li><a class="nav-link" href="features-activities.html">Activities</a></li>
              <li><a class="nav-link" href="features-post-create.html">Post Create</a></li>
              <li><a class="nav-link" href="features-posts.html">Posts</a></li>
              <li><a class="nav-link" href="features-profile.html">Profile</a></li>
              <li><a class="nav-link" href="features-settings.html">Settings</a></li>
              <li><a class="nav-link" href="features-setting-detail.html">Setting Detail</a></li>
              <li><a class="nav-link" href="features-tickets.html">Tickets</a></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link has-dropdown"><i class="fas fa-ellipsis-h"></i> <span>Utilities</span></a>
            <ul class="dropdown-menu">
              <li><a href="utilities-contact.html">Contact</a></li>
              <li><a class="nav-link" href="utilities-invoice.html">Invoice</a></li>
              <li><a href="utilities-subscribe.html">Subscribe</a></li>
            </ul>
          </li>
          <li><a class="nav-link" href="credits.html"><i class="fas fa-pencil-ruler"></i> <span>Credits</span></a></li>
        </ul> -->

        <div class="mt-4 mb-4 p-3 hide-sidebar-mini">
          <a href="https://getstisla.com/docs" class="btn btn-primary btn-lg btn-block btn-icon-split">
            <i class="fas fa-rocket"></i> Documentation
          </a>
        </div>
    </aside>
  </div>